<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class ClusterSementara extends Seeder
{

    public function run()
    {
        $data = [
            // Cluster A            
            [
                'jalur'       => 'A.1.01',
                'jumlah_box' => 80,
                'keterangan' => '',
                'gd_setting' => 'GD SETTING',
                'status'     => '',
            ],
            [
                'jalur'       => 'A.1.02',
                'jumlah_box' => 80,
                'keterangan' => '',
                'gd_setting' => 'GD SETTING',
                'status'     => '',
            ],
            [
                'jalur'       => 'A.1.03',
                'jumlah_box' => 80,
                'keterangan' => '',
                'gd_setting' => 'GD SETTING',
                'status'     => '',
            ],
            [
                'jalur'       => 'A.1.04',
                'jumlah_box' => 80,
                'keterangan' => '',
                'gd_setting' => 'GD SETTING',
                'status'     => '',
            ],
            [
                'jalur'       => 'A.1.05',
                'jumlah_box' => 80,
                'keterangan' => '',
                'gd_setting' => 'GD SETTING',
                'status'     => '',
            ],
            [
                'jalur'       => 'A.1.06',
                'jumlah_box' => 80,
                'keterangan' => '',
                'gd_setting' => 'GD SETTING',
                'status'     => '',
            ],
            [
                'jalur'       => 'A.1.07',
                'jumlah_box' => 80,
                'keterangan' => '',
                'gd_setting' => 'GD SETTING',
                'status'     => '',
            ],
            [
                'jalur'       => 'A.1.08',
                'jumlah_box' => 80,
                'keterangan' => '',
                'gd_setting' => 'GD SETTING',
                'status'     => '',
            ],
            [
                'jalur'       => 'A.1.09',
                'jumlah_box' => 80,
                'keterangan' => '',
                'gd_setting' => 'GD SETTING',
                'status'     => '',
            ],
            [
                'jalur'       => 'A.1.10',
                'jumlah_box' => 80,
                'keterangan' => '',
                'gd_setting' => 'GD SETTING',
                'status'     => '',
            ],
            [
                'jalur'       => 'A.2.01',
                'jumlah_box' => 80,
                'keterangan' => '',
                'gd_setting' => 'GD SETTING',
                'status'     => '',
            ],
            [
                'jalur'       => 'A.2.02',
                'jumlah_box' => 80,
                'keterangan' => '',
                'gd_setting' => 'GD SETTING',
                'status'     => '',
            ],
            [
                'jalur'       => 'A.2.03',
                'jumlah_box' => 80,
                'keterangan' => '',
                'gd_setting' => 'GD SETTING',
                'status'     => '',
            ],
            [
                'jalur'       => 'A.2.04',
                'jumlah_box' => 80,
                'keterangan' => '',
                'gd_setting' => 'GD SETTING',
                'status'     => '',
            ],
            [
                'jalur'       => 'A.2.05',
                'jumlah_box' => 80,
                'keterangan' => '',
                'gd_setting' => 'GD SETTING',
                'status'     => '',
            ],
            [
                'jalur'       => 'A.2.06',
                'jumlah_box' => 80,
                'keterangan' => '',
                'gd_setting' => 'GD SETTING',
                'status'     => '',
            ],
            [
                'jalur'       => 'A.2.07',
                'jumlah_box' => 80,
                'keterangan' => '',
                'gd_setting' => 'GD SETTING',
                'status'     => '',
            ],
            [
                'jalur'       => 'A.2.08',
                'jumlah_box' => 80,
                'keterangan' => '',
                'gd_setting' => 'GD SETTING',
                'status'     => '',
            ],
            [
                'jalur'       => 'A.2.09',
                'jumlah_box' => 80,
                'keterangan' => '',
                'gd_setting' => 'GD SETTING',
                'status'     => '',
            ],
            [
                'jalur'       => 'A.2.10',
                'jumlah_box' => 80,
                'keterangan' => '',
                'gd_setting' => 'GD SETTING',
                'status'     => '',
            ],
            // Cluster B
            [
                'jalur'       => 'B.1.01',
                'jumlah_box' => 80,
                'keterangan' => '',
                'gd_setting' => 'GD SETTING',
                'status'     => '',
            ],
            [
                'jalur'       => 'B.1.02',
                'jumlah_box' => 80,
                'keterangan' => '',
                'gd_setting' => 'GD SETTING',
                'status'     => '',
            ],
            [
                'jalur'       => 'B.1.03',
                'jumlah_box' => 80,
                'keterangan' => '',
                'gd_setting' => 'GD SETTING',
                'status'     => '',
            ],
            [
                'jalur'       => 'B.1.04',
                'jumlah_box' => 80,
                'keterangan' => '',
                'gd_setting' => 'GD SETTING',
                'status'     => '',
            ],
            [
                'jalur'       => 'B.1.05',
                'jumlah_box' => 80,
                'keterangan' => '',
                'gd_setting' => 'GD SETTING',
                'status'     => '',
            ],
            [
                'jalur'       => 'B.1.06',
                'jumlah_box' => 80,
                'keterangan' => '',
                'gd_setting' => 'GD SETTING',
                'status'     => '',
            ],
            [
                'jalur'       => 'B.1.07',
                'jumlah_box' => 80,
                'keterangan' => '',
                'gd_setting' => 'GD SETTING',
                'status'     => '',
            ],
            [
                'jalur'       => 'B.1.08',
                'jumlah_box' => 80,
                'keterangan' => '',
                'gd_setting' => 'GD SETTING',
                'status'     => '',
            ],
            [
                'jalur'       => 'B.1.09',
                'jumlah_box' => 80,
                'keterangan' => '',
                'gd_setting' => 'GD SETTING',
                'status'     => '',
            ],
            [
                'jalur'       => 'B.1.10',
                'jumlah_box' => 80,
                'keterangan' => '',
                'gd_setting' => 'GD SETTING',
                'status'     => '',
            ],
            [
                'jalur'       => 'B.2.01',
                'jumlah_box' => 80,
                'keterangan' => '',
                'gd_setting' => 'GD SETTING',
                'status'     => '',
            ],
            [
                'jalur'       => 'B.2.02',
                'jumlah_box' => 80,
                'keterangan' => '',
                'gd_setting' => 'GD SETTING',
                'status'     => '',
            ],
            [
                'jalur'       => 'B.2.03',
                'jumlah_box' => 80,
                'keterangan' => '',
                'gd_setting' => 'GD SETTING',
                'status'     => '',
            ],
            [
                'jalur'       => 'B.2.04',
                'jumlah_box' => 80,
                'keterangan' => '',
                'gd_setting' => 'GD SETTING',
                'status'     => '',
            ],
            [
                'jalur'       => 'B.2.05',
                'jumlah_box' => 80,
                'keterangan' => '',
                'gd_setting' => 'GD SETTING',
                'status'     => '',
            ],
            [
                'jalur'       => 'B.2.06',
                'jumlah_box' => 80,
                'keterangan' => '',
                'gd_setting' => 'GD SETTING',
                'status'     => '',
            ],
            [
                'jalur'       => 'B.2.07',
                'jumlah_box' => 80,
                'keterangan' => '',
                'gd_setting' => 'GD SETTING',
                'status'     => '',
            ],
            [
                'jalur'       => 'B.2.08',
                'jumlah_box' => 80,
                'keterangan' => '',
                'gd_setting' => 'GD SETTING',
                'status'     => '',
            ],
            [
                'jalur'       => 'B.2.09',
                'jumlah_box' => 80,
                'keterangan' => '',
                'gd_setting' => 'GD SETTING',
                'status'     => '',
            ],
            [
                'jalur'       => 'B.2.10',
                'jumlah_box' => 80,
                'keterangan' => '',
                'gd_setting' => 'GD SETTING',
                'status'     => '',
            ],
            // Cluster C
            [
                'jalur'       => 'C.1.01',
                'jumlah_box' => 80,
                'keterangan' => '',
                'gd_setting' => 'GD SETTING',
                'status'     => '',
            ],
            [
                'jalur'       => 'C.1.02',
                'jumlah_box' => 80,
                'keterangan' => '',
                'gd_setting' => 'GD SETTING',
                'status'     => '',
            ],
            [
                'jalur'       => 'C.1.03',
                'jumlah_box' => 80,
                'keterangan' => '',
                'gd_setting' => 'GD SETTING',
                'status'     => '',
            ],
            [
                'jalur'       => 'C.1.04',
                'jumlah_box' => 80,
                'keterangan' => '',
                'gd_setting' => 'GD SETTING',
                'status'     => '',
            ],
            [
                'jalur'       => 'C.1.05',
                'jumlah_box' => 80,
                'keterangan' => '',
                'gd_setting' => 'GD SETTING',
                'status'     => '',
            ],
            [
                'jalur'       => 'C.1.06',
                'jumlah_box' => 80,
                'keterangan' => '',
                'gd_setting' => 'GD SETTING',
                'status'     => '',
            ],
            [
                'jalur'       => 'C.1.07',
                'jumlah_box' => 80,
                'keterangan' => '',
                'gd_setting' => 'GD SETTING',
                'status'     => '',
            ],
            [
                'jalur'       => 'C.1.08',
                'jumlah_box' => 80,
                'keterangan' => '',
                'gd_setting' => 'GD SETTING',
                'status'     => '',
            ],
            [
                'jalur'       => 'C.1.09',
                'jumlah_box' => 80,
                'keterangan' => '',
                'gd_setting' => 'GD SETTING',
                'status'     => '',
            ],
            [
                'jalur'       => 'C.1.10',
                'jumlah_box' => 80,
                'keterangan' => '',
                'gd_setting' => 'GD SETTING',
                'status'     => '',
            ],
            [
                'jalur'       => 'C.2.01',
                'jumlah_box' => 80,
                'keterangan' => '',
                'gd_setting' => 'GD SETTING',
                'status'     => '',
            ],
            [
                'jalur'       => 'C.2.02',
                'jumlah_box' => 80,
                'keterangan' => '',
                'gd_setting' => 'GD SETTING',
                'status'     => '',
            ],
            [
                'jalur'       => 'C.2.03',
                'jumlah_box' => 80,
                'keterangan' => '',
                'gd_setting' => 'GD SETTING',
                'status'     => '',
            ],
            [
                'jalur'       => 'C.2.04',
                'jumlah_box' => 80,
                'keterangan' => '',
                'gd_setting' => 'GD SETTING',
                'status'     => '',
            ],
            [
                'jalur'       => 'C.2.05',
                'jumlah_box' => 80,
                'keterangan' => '',
                'gd_setting' => 'GD SETTING',
                'status'     => '',
            ],
            [
                'jalur'       => 'C.2.06',
                'jumlah_box' => 80,
                'keterangan' => '',
                'gd_setting' => 'GD SETTING',
                'status'     => '',
            ],
            [
                'jalur'       => 'C.2.07',
                'jumlah_box' => 80,
                'keterangan' => '',
                'gd_setting' => 'GD SETTING',
                'status'     => '',
            ],
            [
                'jalur'       => 'C.2.08',
                'jumlah_box' => 80,
                'keterangan' => '',
                'gd_setting' => 'GD SETTING',
                'status'     => '',
            ],
            [
                'jalur'       => 'C.2.09',
                'jumlah_box' => 80,
                'keterangan' => '',
                'gd_setting' => "GD SETTING",
                "status"     => "",
            ],
            [
                "jalur"       => "C.2.10",
                "jumlah_box"     => 80,
                "keterangan"     => "",
                "gd_setting"     => "GD SETTING",
                "status"         => "",
            ],
        ];
        // Masukkan data ke dalam tabel layout
        $this->db->table('layout')->insertBatch($data);
    }
}
